version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAMan15NovProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser
  gitUsername: siqagituser
  gitBranch: main
- name: WmJDBCAdapter
  wpmServer: https://packages.webmethods.io
  wpmRegistry: softwareag
services:
- serviceName: project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_15Nov
  packages:
  - name: SIQAMan15NovProject
    version: "1.0"
- serviceName: project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBTest
  packages:
  - name: SIQAMan15NovProject
    version: "1.0"
- serviceName: project.siqaman15nov.integrations:SIQAAdapterFlow
  packages:
  - name: SIQAMan15NovProject
    version: "1.0"
- serviceName: project.siqaman15nov.integrations:Sum
  packages:
  - name: SIQAMan15NovProject
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.1.0.0.2020
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2020
- serviceName: project.siqaman15nov.integrations:deepclonetest
  packages:
  - name: SIQAMan15NovProject
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2020
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2020
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2020
configurationVariables:
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionSettings.dbType
  : MSSQL
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionEnabled
  : "false"
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionManagerSettings.maximumPoolSize
  : "10"
  jdbc.jdbcTestPool.spyenabled: "false"
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  jdbc.jdbcTestPool.snoopenabled: "false"
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionSettings.trustStore
  : ""
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionSettings.keyStore
  : ""
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionSettings.transactionType
  : NO_TRANSACTION
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionSettings.portNumber
  : "1433"
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionSettings.user
  : sa
  jdbc.jdbcTestPool.expireTime: "60000"
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionManagerSettings.expireTimeout
  : "1000"
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionManagerSettings.minimumPoolSize
  : "1"
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionSettings.password
  : "{AES}B2Xqma4Ost5nVUiXctJydQ=="
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionSettings.driverType
  : Progress® DataDirect®
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQAMan15NovProject.project.siqaman15nov.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_15Nov.connectionSettings.serverName
  : vmiboint01
  jdbc.jdbcTestPool.useSSL: "false"
